---
title: "Lead Violations"
author: "Brook Frye"
date: "4/11/23"
output: html_document
---

```{r setup, include=FALSE}
source("code/utils/00_load_dependencies.R")
source("code/utils/make_cd.R")
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

Housing Maintenance Code Violations - lead based paint hazard
```{r include=FALSE}
hmcv_sub <- fread("data/lead_data_hmcv_4_11_23.csv")
hmcv_sub[, inspectiondate := as.Date(inspectiondate)]
hmcv_sub[, yearinspect := year(inspectiondate)]

# check nas
hmcv_sub[streetname %in% "FOREST AVENUE" & housenumber %in% "861", councildistrict :=  49]
hmcv_sub[streetname %in% "BEACH 88 STREET", councildistrict :=  32]
hmcv_sub[streetname %in% "GRAND CENTRAL PARKWAY SOUTH", councildistrict :=  24]
hmcv_sub[streetname %in% "ADAM CLAYTONPOWELL JR BOULEVARD", councildistrict :=  9]

lead_paint <- hmcv_sub[grep("SECTION 27-2056.6", novdescription, ignore.case = TRUE), .(violationid, inspectiondate, CounDist=councildistrict, yearinspect)]

# number of violations per year by cd
lead_paint_cd <- lead_paint[, .(vios_cd = length(unique(violationid))), by = .(CounDist, yearinspect)]

# number of violations per day citywide
lead_paint_vios_day <- lead_paint[, .(vios_day = .N), by = .(inspectiondate)]

```

```{r echo=FALSE}
# get number of buildings / CD
pluto_file <- fread("https://data.cityofnewyork.us/resource/64uk-42ks.csv?$limit=99999999") 

pluto_sub <- pluto_file[unitsres > 0, .(
    bbl = str_sub(as.character(bbl), 1, 10),
    CounDist = council)]

bbls_cd <- unique(pluto_sub[, .N, by = .(CounDist)])
lead_paint_sub <- unique(lead_paint[yearinspect >= 2020, ])
lead_paint_sub[, vios_cd := length(unique(violationid)), by = .(CounDist)]

lead_map <- unique(merge(lead_paint_sub[ ,.(CounDist, vios_cd)], bbls_cd))
lead_map[, norm_vios_cd := (vios_cd/N)*1000]
setnames(lead_map, "CounDist", "coun_dist")

council_districts <- read_sf("data/City Council Districts/") %>% st_transform('+proj=longlat +datum=WGS84' )


lead_sf <- left_join(lead_map, council_districts) %>% st_as_sf() 

pal = colorNumeric(
  palette = "Blues",
  domain = lead_map$norm_vios_cd
)

l <-  leaflet(data = lead_sf) %>%
  addCouncilStyle() %>%
        addPolygons(weight=1,
        col=~pal(norm_vios_cd),
              fillOpacity = .7,
              popup = paste0("<strong>Number of violations: </strong>",
                             lead_map$vios_cd, "<br>"))



l <- l %>% leaflet::addPolygons(data = dists, fill = FALSE, weight = 1, 
      color = "#2F56A6", opacity = .5, smoothFactor = 0, 
      group = "Council Districts") %>%
      leaflet::addLabelOnlyMarkers(data = dists, lat = ~lab_y, lng = ~lab_x, label = ~coun_dist,
      labelOptions = leaflet::labelOptions(permanent = TRUE, noHide = TRUE,
       textOnly = TRUE,
       textsize = 12, direction = "center", style = list(color = "#23417D",
"font-family" = "'Open Sans', sans-serif",
"font-weight" = "bold"))) %>%
  addLegend("topleft", 
            pal = pal, values = unique(lead_map$norm_vios_cd), 
            title = "Lead Paint Violations per building: 2020-Present", 
            opacity = 1, 
            position = "topleft")

saveWidget(l, "lead_violations_by-cd_2023.html")


```

Data Source: https://data.cityofnewyork.us/Housing-Development/Housing-Maintenance-Code-Violations/wvxf-dwi5