---
title: "02_litigations_lead_maps"
output: html_document
date: "2023-04-21"
---

Run 01_litigations_lead.Rmd first.

```{r}
# ---- MAP 1 ----
# ---- merge lead data w/ council district shp
council_districts <- council_districts %>%
  rename("council_district" = "CounDist")
lead_lit_cd <- lead_litigations %>% full_join(y = council_districts, by = 'council_district') %>%
                st_as_sf() 
lead_lit_cd <- lead_lit_cd[lead_lit_cd$council_district != 51,] # removing this one because there's no obs. in cd 51...
```

```{r}
# ---- MAP 1 ----
# ---- group sums, set up color palette
lead_lit_cd_sums <- lead_lit_cd %>% group_by(geometry, council_district) %>% summarise(count=n())

pal = colorBin(
  palette = rev(nycc_pal("cool")(100)),
  domain = lead_lit_cd_sums$count, 
  na.color = "White", 
  reverse = FALSE
)
```

```{r}
# ---- MAP 1 ----
# ---- all lead litigations on opendata, compiled since august 2006
all_leadlit <- leaflet() %>%
  addCouncilStyle(add_dists = TRUE) %>%
  addPolygons(data=lead_lit_cd_sums, weight=1, col=~pal(count), fillOpacity = .7,
              popup = paste0("<strong>Number of litigations: </strong>", 
                             lead_lit_cd_sums$count, "<br>")) %>%
  addLegend("topleft", pal = pal, values = unique(lead_lit_cd_sums$count), 
            title = "Lead Litigations: 2006-Present", opacity = 1, position = "topleft") 
```

```{r}
# ---- MAP 1 ----
# ---- save map 1
saveWidget(all_leadlit, file=file.path('visuals/april_2023', 
                               "lead_litigations_by_cd.html"))
mapshot(all_leadlit, file = "visuals/april_2023/lead_litigations_by_cd.png")
```

```{r}
# ---- MAP 2 ----
# ---- circle map format and palette
circle_map <- distinct(lead_litigations) %>%
  mutate(addr = paste(housenumber, streetname))

pal2 = colorBin(
  palette = rev(nycc_pal("cool")(100)),
  domain = circle_map$lit_bbl,
  reverse = FALSE
)
```

```{r}
# ---- MAP 2 ----
# ---- all lead litigations on opendata, compiled since august 2006
all_leadlit_circlevers <- leaflet() %>% 
  addPolygons(data=council_districts, weight=1, col='#d3d3d3', fillOpacity = 0.2) %>%
  addCouncilStyle(add_dists = TRUE) %>%
  addCircles(data=circle_map,
                 lng=~longitude, lat=~latitude,
                 color = ~pal2(lit_bbl), 
                 popup = paste0("<strong>Number of litigations: </strong>", circle_map$lit_bbl, "<br>",
                                "<strong>Address: </strong>", circle_map$addr, "<br>",
                                "<strong>Respondent: </strong>", circle_map$respondent, "<br>"),
                 group = df,
                 label =  ~paste("Lead Litigations since August 2006:", circle_map$lit_bbl),
                 weight = 2,
                 radius = 1, 
                 stroke = 2, 
                 opacity = .5, 
                 labelOptions = labelOptions(noHide = F,
                 direction = 'auto')) %>% 
   addLegend("topleft", pal = pal2, values = unique(circle_map$lit_bbl), title = "Lead Litigations: 2006-Present", opacity = 1, position = "topleft")
```

```{r}
# ---- MAP 2 ----
# ---- save map 2
saveWidget(all_leadlit_circlevers, file=file.path('visuals/april_2023', 
                               "lead_litigations_by_bbl.html"))
mapshot(all_leadlit_circlevers, file = "visuals/april_2023/lead_litigations_by_bbl.png")
```

```{r}
# ---- MAP 1.5 ----
# ---- merge pluto data with council district shp
pluto_sub <- pluto_sub %>% rename("council_district" = "council_dist")
pluto_sub_cd <- pluto_sub %>% full_join(y = council_districts, by = 'council_district') %>% st_as_sf() 

# ----  get prop of lead litigations per thousand buildings
pluto_sub_cd_sums <- pluto_sub_cd %>% group_by(geometry, council_district) %>% summarise(count=n())
lit_prop <- left_join(lead_lit_cd_sums, pluto_sub_cd_sums %>% as.data.frame() %>% select(-geometry), by = "council_district")
lit_prop$lit_per_thous_bldngs <- (lit_prop$`count.x`/lit_prop$`count.y`)*1000
lit_prop <- lit_prop %>% select('geometry','council_district', lit_per_thous_bldngs)
```

```{r}
# ---- MAP 1.5 ----
# ---- set up color palette
pal = colorBin(
  palette = rev(nycc_pal("cool")(100)),
  domain = lit_prop$lit_per_thous_bldngs, 
  na.color = "White", 
  reverse = FALSE
)
```

```{r}
# ---- MAP 1.5 ----
lit_per_thou <- leaflet() %>% 
  addCouncilStyle(add_dists = TRUE) %>%
  addPolygons(data=lit_prop, weight=1, col=~pal(lit_per_thous_bldngs), fillOpacity = .7,
              popup = paste0("<strong>Number of litigations per thousand buildings: </strong>", round(lit_prop$lit_per_thous_bldngs,2), "<br>")) %>%
  addLegend("topleft", pal=pal, values=unique(lit_prop$lit_per_thous_bldngs), title="Lead Litigations (per Thousand Buildings): 2006-Present", opacity = 1, position = "topleft")
```

```{r}
# ---- MAP 1.5 ----
# ---- save map 1.5
saveWidget(lit_per_thou, file=file.path('visuals/april_2023', 
                               "lead_litigations_per_thsnd_bbl_by_cd.html"))
mapshot(lit_per_thou, file = "visuals/april_2023/lead_litigations_per_thsnd_bbl_by_cd.png")
```

