---
title: "violations_by_boro_redo"
output: html_document
date: "2023-04-18"
---

```{r}
knitr::opts_chunk$set(echo = TRUE)
# source("00_load_dependencies.R")
library(data.table)
```


```{r setup, include=FALSE}
# load data
knitr::opts_chunk$set(echo = TRUE)
hmcv <- fread("https://data.cityofnewyork.us/resource/wvxf-dwi5.csv?$where=inspectiondate>='2018-01-01'&$limit=99999999999")[!currentstatus %in% "VIOLATION DISMISSED"]
```

```{r}
# unique(hmcv$violationstatus)
hmcv <- unique(hmcv[grep("lead", novdescription, ignore.case = TRUE), ])
```

```{r}
hmcv[, inspectiondate := as.Date(inspectiondate)]
setDT(hmcv)[, year_month := format(as.Date(inspectiondate), "%Y-%m") ]
```

```{r}
# hmcv[hmcv$boro != "BRONX"] %>% group_by(inspectiondate) %>% summarise(count=n())
write.csv(hmcv %>% group_by(inspectiondate) %>% summarise(count=n()), "../data/lead-paint_vios_over-time_2.csv", row.names=FALSE)
```

```{r}
# hmcv[hmcv$boro != "BRONX",] %>% group_by(month_year) %>% summarise(count=n())
over_time <- hmcv %>% group_by(year_month) %>% summarise(count=n())
over_time
write.csv(over_time, "../data/lead-paint_vios_over-time-month-year.csv", row.names=FALSE)
```

```{r}
write.csv(hmcv %>% group_by(boro) %>% summarise(count=n()), "../data/lead-paint_vios_by_boro.csv", row.names=FALSE)
```

```{r}
ggplot(data=hmcv, aes(x=year_month)) + geom_bar()
ggplot(data=hmcv %>% group_by(yr), aes(x=yr)) + geom_bar()
```
```{r}
ggplot(data=hmcv %>% group_by(boro), aes(x=boro)) + geom_bar()
ggsave(lead_plot, filename = "../../../visuals/lead_vios_by_boro.png", width = 8, height = 5)
```

