---
title: "02_litigations_lead_layered_map"
output: html_document
date: "2023-04-24"
---
setwd("/Users/rhirota/Documents/GitHub/lead_hearing")
lead / all litigation types by cd 

```{r}
source("code/utils/00_load_dependencies.R")
```

Data Source:
https://data.cityofnewyork.us/Housing-Development/Housing-Litigations/59kj-x8nc

```{r}
# ---- merge lead data w/ council district shp
council_districts <- council_districts %>%
  rename("council_district" = "CounDist")
lead_lit_cd <- lead_litigations %>% full_join(y = council_districts, by = 'council_district') %>%
                st_as_sf() 
lead_lit_cd <- lead_lit_cd[lead_lit_cd$council_district != 51,] # removing this one because there's no obs. in cd 51...
```

```{r}
# ---- merge pluto data with council district shp
pluto_sub <- pluto_sub %>% rename("council_district" = "council_dist")
pluto_sub_cd <- pluto_sub %>% full_join(y = council_districts, by = 'council_district') %>% st_as_sf() 
```

```{r}
# ---- sum litigations (lead, all)
lead_lit_cd_sums <- lead_lit_cd %>% group_by(geometry, council_district) %>% summarise(lead_litigations=n())
# lit_cd_sums <- lit_cd %>% group_by(geometry, council_district) %>% summarise(count=n())
```

---- IGNORE ----
```{r}
# # ---- rejoin the two litigation dfs
# lead_over_all_lits_cd <- left_join(lit_cd_sums, lead_lit_cd_sums %>% as.data.frame() %>% select(-geometry), by = "council_district")
# lead_over_all_lits_cd$prop_lead <- lead_over_all_lits_cd$count.y/lead_over_all_lits_cd$count.x
# lead_over_all_lits_cd <- lead_over_all_lits_cd[complete.cases(lead_over_all_lits_cd$prop_lead), ]
```
---- IGNORE ----

```{r}
# ----  get prop of lead litigations per thousand buildings
pluto_sub_cd_sums <- pluto_sub_cd %>% group_by(geometry, council_district) %>% summarise(bbl=n())
lit_prop <- left_join(lead_lit_cd_sums, pluto_sub_cd_sums %>% as.data.frame() %>% select(-geometry), by = "council_district")
lit_prop$lit_per_thous_bldngs <- (lit_prop$lead_litigations/lit_prop$bbl)*1000
lit_prop <- lit_prop %>% select('geometry','council_district', lit_per_thous_bldngs, bbl, lead_litigations)
```

```{r}
# ---- merge with % under 6 years shp
master <- left_join(lit_prop, under_six_shp %>% as.data.frame() %>% select(-geometry), by = "council_district")
master_short <- master %>% select('geometry','council_district', lit_per_thous_bldngs, bbl, lead_litigations, `Percent.Under.6`)
```

```{r}
# ---- set up color palettes for mapping
child_pal = colorBin(
  palette = rev(nycc_pal("warm")(100)),
  domain = master_short$`Percent.Under.6`,
  na.color = "White",
  reverse = FALSE
)
per_thousnd_pal = colorBin(
  palette = rev(nycc_pal("cool")(100)),
  domain = master_short$lit_per_thous_bldngs,
  na.color = "White",
  reverse = FALSE
)
```

```{r}
# --- MAP 1 ----
# ---- layer 1: pct of population <6 years old
# ---- layer 2: lead litigations per thousand buildings
age_thousand_map <- leaflet() %>%
  addCouncilStyle(add_dists = TRUE) %>%
  addPolygons(data=master_short, weight=1, col=~child_pal(`Percent.Under.6`), fillOpacity = .6,
              popup = paste0("<strong>Percent of Population under 6 (years): </strong>", master_short$Percent.Under.6, "<br>",
                "<strong>Number of HPD lead litigations: </strong>", master_short$lead_litigations, "<br>",
                "<strong>Lead litigations per thousand buildings: </strong>", 
                round(master_short$lit_per_thous_bldngs,2), "<br>"),
              group="Children") %>%
  
  addPolygons(data=master_short, weight=1, col=~per_thousnd_pal(lit_per_thous_bldngs), fillOpacity = .6,
              popup = paste0("<strong>Percent of Population under 6 (years): </strong>", master_short$Percent.Under.6, "<br>",
                "<strong>Number of HPD lead litigations: </strong>", master_short$lead_litigations, "<br>",
                "<strong>Lead litigations per thousand buildings: </strong>", 
                round(master_short$lit_per_thous_bldngs,2), "<br>"),
              group="Per thousand buildings") %>%
  
  addLegend("topleft", pal = child_pal, values = unique(master_short$`Percent.Under.6`),
            title = "Percent of Population <6 Years Old", opacity = 1, position = "topleft", group="Children") %>%
  
  addLegend("topleft", pal = per_thousnd_pal, values = unique(master_short$lit_per_thous_bldngs),
            title = "Litigations per Thousand Buildings: 2006-Present", opacity = 1, position = "topleft", group="Per thousand buildings") %>%
  
  addLayersControl(
    # baseGroups = c("Num"),
    overlayGroups = c("Per thousand buildings"),
    options = layersControlOptions(collapsed = FALSE)
  )
```

---- IGNORE ----
```{r}
# ---- set up color palettes for mapping
# pal = colorBin(
#   palette = rev(nycc_pal("cool")(100)),
#   domain = lead_over_all_lits_cd$prop_lead, 
#   na.color = "White", 
#   reverse = FALSE
# )
# pal2 = colorBin(
#   palette = rev(nycc_pal("warm")(100)),
#   domain = lead_lit_cd_sums$count, 
#   na.color = "White", 
#   reverse = FALSE
# )
```
```{r}
# # ---- MAP 1 ----
# # ---- % lead litigations of all HPD litigations
# prop_of_lits <- leaflet() %>%
#   addCouncilStyle(add_dists = TRUE) %>%
#   addPolygons(data=lead_over_all_lits_cd, weight=1, col=~pal(prop_lead), fillOpacity = .7,
#               popup = paste0("<strong>Percentage lead-related (of all litigations): </strong>", 
#                              round(lead_over_all_lits_cd$prop_lead*100,2),"%", "<br>"))%>%
#   addLegend("topleft", pal=pal, values=unique(lead_over_all_lits_cd$prop_lead), title="Lead Litigations", opacity = 1, position = "topleft")
# # ---- save map 1
# saveWidget(prop_of_lits, file=file.path('visuals/april_2023', 
#                                "pct_lead_of_all_lits_by_cd.html"))
# mapshot(prop_of_lits, file = "visuals/april_2023/pct_lead_of_all_lits_by_cd.png")
```
```{r}
# # ---- MAP 2 ----
# # ---- base layer: number of lead litigations
# # ---- overlay: % lead litigations of all HPD litigations
# num_and_pct_lits <- leaflet() %>%
#   addCouncilStyle(add_dists = TRUE) %>%
#   addPolygons(data=lead_lit_cd_sums, weight=1, col=~pal2(count), fillOpacity = .6,
#               popup = paste0("<strong>Number of HPD lead litigations: </strong>", 
#                              lead_lit_cd_sums$count, "<br>"), 
#               group="Num") %>%
#   addPolygons(data=lead_over_all_lits_cd, weight=1, col=~pal(prop_lead), fillOpacity = .55,
#               popup = paste0("<strong>Percent of total HPD litigations: </strong>", 
#                              round(lead_over_all_lits_cd$prop_lead*100,2),"%", "<br>", 
#                              "<strong>Number of lead litigations: </strong>", lead_over_all_lits_cd$`count.y`, "<br>"),
#               group="Percent of HPD Total") %>%
#   addLegend("topleft", pal = pal2, values = unique(lead_lit_cd_sums$count), 
#             title = "Number of Litigations: 2006-Present", opacity = 1, position = "topleft", group="Num") %>%
#   addLegend("topleft", pal = pal, values = unique(lead_over_all_lits_cd$prop_lead), 
#             title = "Percent of HPD Total: 2006-Present", opacity = 1, position = "topleft", group="Percent of HPD Total") %>%
#   addLayersControl(
#     # baseGroups = c("Num"),
#     overlayGroups = c("Percent of HPD Total"),
#     options = layersControlOptions(collapsed = FALSE)
#   ) 
# # ---- save map 1
# saveWidget(num_and_pct_lits, file=file.path('visuals/april_2023', 
#                                "pct_lits_layered_over_num_lits_by_cd.html"))
# mapshot(num_and_pct_lits, file = "visuals/april_2023/pct_lits_layered_over_num_lits_by_cd.png")
# ```
# 
# 
# ```{r}
# setwd("/Users/rhirota/Documents/GitHub/lead_hearing")
# under_six_df <- read.csv('data/input/council-estimates_under-6.csv')
# # make geometry column a list to convert into spatial
# under_six_df$geometry <- as.list(under_six_df$geometry)
# # make into a spatial object
# under_six_shp <- under_six_df %>% st_as_sf()  
# st_crs(under_six_shp) <- 4326
# ```
# 
# ```{r}
# under_six_shp
# ```
# 
# 
# ```{r}
# master <- left_join(lead_over_all_lits_cd, under_six_shp %>% as.data.frame() %>% select(-geometry), by = "council_district")
# ```
# 
# ```{r}
# master$pct_lead <- master$prop_lead*100
# ```
# 
# 
# ```{r}
# child_pal = colorBin(
#   palette = rev(nycc_pal("warm")(100)),
#   domain =  master$`Percent.Under.6`, 
#   na.color = "White", 
#   reverse = FALSE
# )
# prop_pal = colorBin(
#   palette = rev(nycc_pal("cool")(100)),
#   domain = master$prop_lead, 
#   na.color = "White", 
#   reverse = FALSE
# )
# pct_pal = colorBin(
#   palette = rev(nycc_pal("cool")(100)),
#   domain = master$pct_lead, 
#   na.color = "White", 
#   reverse = FALSE
# )
# num_pal = colorBin(
#   palette = rev(nycc_pal("cool")(100)),
#   domain = master$`count.y`, 
#   na.color = "White", 
#   reverse = FALSE
# )
# ```
# 
# ```{r}
# three_layer <- leaflet() %>%
#   addCouncilStyle(add_dists = TRUE) %>%
#   addPolygons(data=master, weight=1, col=~child_pal(`Percent.Under.6`), fillOpacity = .6,
#               popup = paste0("<strong>Percent of Population under 6 (years): </strong>", 
#                              master$`Percent.Under.6`, "%","<br>",
#                              "<strong>Percent of total HPD litigations: </strong>", 
#                              round(master$pct_lead,2),"%", "<br>", 
#                              "<strong>Number of HPD lead litigations: </strong>", 
#                              master$`count.y`, "<br>"), 
#               group="Base") %>%
# 
# 
#   # addPolygons(data=master, weight=1, col=~num_pal(`count.y`), fillOpacity = .35,
#   #             popup = paste0("<strong>Percent of Population under 6 (years): </strong>", 
#   #                            master$`Percent.Under.6`, "%","<br>",
#   #                            "<strong>Percent of total HPD litigations: </strong>", 
#   #                            round(master$prop_lead*100,2),"%", "<br>", 
#   #                            "<strong>Number of HPD lead litigations: </strong>", 
#   #                            master$`count.y`, "<br>"), 
#   #             group="Number of Litigations") %>%
#   
#   addPolygons(data=master, weight=1, col=~pct_pal(pct_lead), fillOpacity = .55,
#               popup = paste0("<strong>Percent of Population under 6 (years): </strong>", 
#                              master$`Percent.Under.6`, "%","<br>",
#                              "<strong>Percent of total HPD litigations: </strong>", 
#                              round(master$pct_lead,2),"%", "<br>", 
#                              "<strong>Number of HPD lead litigations: </strong>", 
#                              master$`count.y`, "<br>"), 
#               group="Percent of HPD Total") %>%
#   
#   addLegend("topleft", pal = child_pal, values = paste0(unique(master$`Percent.Under.6`),"%"), 
#             title = "Percent of Population <6 Years Old", opacity = 1, 
#             position = "topleft", group="Base") %>%
#   
#   addLegend("topleft", pal = pct_pal, values = unique(master$pct_lead), 
#             title = "Percent of HPD Total: 2006-Present", opacity = 1, position = "topleft", 
#             group="Percent of HPD Total") %>%
#   
#    # addLegend("topleft", pal = num_pal, values = unique(master$`count.y`), 
#    #          title = "Number of Litigations: 2006-Present", opacity = 1, position = "topleft", 
#    #          group="Number of Litigations") %>%
#   
#   addLayersControl(
#     # baseGroups = c("Num"),
#     overlayGroups = c("Percent of HPD Total"),
#     options = layersControlOptions(collapsed = FALSE)
#   ) 
```
```{r}
# saveWidget(three_layer, file=file.path('visuals/april_2023', 
#                                "num_pct_agebase_by_cd.html"))
# mapshot(three_layer, file = "visuals/april_2023/num_pct_agebase_by_cd.png")
```
---- IGNORE ----

```{r}
# ---- save map
saveWidget(age_thousand_map, file=file.path('visuals/april_2023',"age_num_per_thousand_by_cd.html"))
mapshot(age_thousand_map, file = "visuals/april_2023/age_num_per_thousand_by_cd.png")
```
