---
title: "violations_by_boro_redo"
output: html_document
date: "2023-04-18"
---

```{r}
knitr::opts_chunk$set(echo = TRUE)
# source("00_load_dependencies.R")
library(data.table)
```

```{r setup, include=FALSE}
# load data
knitr::opts_chunk$set(echo = TRUE)
hmcv <- fread("https://data.cityofnewyork.us/resource/wvxf-dwi5.csv?$where=inspectiondate>='2018-01-01'&$limit=99999999999")[!currentstatus %in% "VIOLATION DISMISSED"]
```

```{r}
# unique(hmcv$violationstatus)
hmcv <- unique(hmcv[grep("lead", novdescription, ignore.case = TRUE), ])
```

```{r}
hmcv[, inspectiondate := as.Date(inspectiondate)]
setDT(hmcv)[, year_month := format(as.Date(inspectiondate), "%Y-%m") ]
```

```{r}
# hmcv[hmcv$boro != "BRONX"] %>% group_by(inspectiondate) %>% summarise(count=n())
write.csv(hmcv %>% group_by(inspectiondate) %>% summarise(count=n()), "../data/lead-paint_vios_over-time_2.csv", row.names=FALSE)
```

```{r}
# hmcv[hmcv$boro != "BRONX",] %>% group_by(month_year) %>% summarise(count=n())
over_time <- hmcv %>% group_by(year_month) %>% summarise(count=n())
# over_time
write.csv(over_time, "../data/lead-paint_vios_over-time-month-year_2.csv", row.names=FALSE)
# hmcv[hmcv$boro != "BRONX",] %>% group_by(inspectiondate) %>% summarise(count=n())
```

```{r}
write.csv(hmcv %>% group_by(boro) %>% summarise(count=n()), "../data/lead-paint_vios_by_boro.csv", row.names=FALSE)
```

```{r}
ggplot(data=hmcv, aes(x=year_month)) + geom_bar()
ggplot(data=hmcv %>% group_by(yr), aes(x=yr)) + geom_bar()
```
```{r}
vios_by_boro <- ggplot(data=hmcv %>% group_by(boro), aes(x=boro)) + geom_bar()
ggsave(vios_by_boro, filename = "../visuals/april_2023/lead_vios_by_boro.png", width = 8, height = 5)
```

```{r}
write.csv(hmcv[hmcv$yr == 2022] %>% group_by(boro) %>% summarise(count=n()), "../data/lead-paint_vios_by_boro_2022.csv", row.names=FALSE)
ggplot(data=hmcv[hmcv$yr == 2022] %>% group_by(boro), aes(x=boro)) + geom_bar()
ggsave(vios_by_boro, filename = "../visuals/april_2023/lead_vios_by_boro_2022.png", width = 8, height = 5)
```


```{r}
# hmcv[, novissueddate := as.Date(novissueddate)]
# setDT(hmcv)[, year_month_issued := format(as.Date(novissueddate), "%Y-%m") ]
# write.csv(hmcv %>% group_by(year_month_issued) %>% summarise(count=n()), "../data/lead-paint_vios_over-time-month-year_issued_2.csv", row.names=FALSE)
```

```{r}
pluto_file <- fread("https://data.cityofnewyork.us/resource/64uk-42ks.csv?$limit=99999999")
pluto_sub <- pluto_file[unitsres > 0, .(
    bbl = str_sub(as.character(bbl), 1, 10),
    res_units = unitsres,
    borough = borough)]
# pluto_sub[, .N, by = .(borough)]
```

```{r}
by_boro <- hmcv %>% group_by(boro) %>% summarise(count=n())
pluto_sub <- pluto_sub %>% 
         rename("boro" = "borough")
pluto_sub <- pluto_sub %>% mutate(boro=recode(boro, "BK" = "BROOKLYN",
               "MN" = "MANHATTAN",
               "QN" = "QUEENS",
               "BX" = "BRONX",
               "SI" = "STATEN ISLAND"))
# unique(pluto_sub$boro)
# unique(by_boro$boro)
```


```{r}
by_boro_normalized <- pluto_sub %>% group_by(boro) %>% summarise(bldngs=n()) %>% full_join(y = by_boro, by = 'boro')
```

```{r}
by_boro_normalized
```

```{r}
by_boro_normalized$per_thousand_bldngs <- (by_boro_normalized$count/(by_boro_normalized$bldngs))
by_boro_normalized$per_thousand_bldngs <- by_boro_normalized$per_thousand_bldngs*1000
by_boro_normalized
```

```{r}
units_by_boro <- pluto_sub %>% group_by(boro) %>% summarise(units = sum(res_units))
by_boro_normalized <- units_by_boro %>% full_join(y = by_boro_normalized, by = 'boro')
```

```{r}
by_boro_normalized$per_thousand_units <- (by_boro_normalized$count/(by_boro_normalized$units))*1000
write.csv(by_boro_normalized, "../data/lead-paint_vios_by_boro.csv", row.names=FALSE)
```


